# Generated by Django 6.1.1 on 2026-09-19 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosigno',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registrosigno',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='api.paciente'),
        ),
        migrations.AlterField(
            model_name='registrosigno',
            name='valor_medido',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
