# Generated by Django 6.1.1 on 2026-09-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposigno',
            options={'verbose_name': 'Tipo de Signo', 'verbose_name_plural': 'Tipos de Signo'},
        ),
        migrations.AlterField(
            model_name='tiposigno',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
