# Generated by Django 6.1.1 on 2026-09-22 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_registrosigno_fecha_hora_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrosigno",
            name="responsable",
        ),
        migrations.RemoveField(
            model_name="registrosigno",
            name="valor_medido",
        ),
        migrations.AddField(
            model_name="registrosigno",
            name="valor",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paciente",
            name="apellidos",
            field=models.CharField(max_length=100, verbose_name="Apellidos"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="documento",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Documento de Identidad"
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="edad",
            field=models.IntegerField(verbose_name="Edad"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="eps",
            field=models.CharField(max_length=100, verbose_name="EPS"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="genero",
            field=models.CharField(max_length=10, verbose_name="Género"),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="nombres",
            field=models.CharField(max_length=100, verbose_name="Nombres"),
        ),
        migrations.AlterField(
            model_name="registrosigno",
            name="dispositivo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registros",
                to="api.dispositivo",
            ),
        ),
        migrations.AlterField(
            model_name="registrosigno",
            name="tipo_signo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registros",
                to="api.tiposigno",
            ),
        ),
    ]
