# Generated by Django 6.1.1 on 2026-09-22 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_registrosigno_fecha_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosigno',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='registrosigno',
            name='valor_medido',
        ),
        migrations.AddField(
            model_name='registrosigno',
            name='valor',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrosigno',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='api.dispositivo'),
        ),
        migrations.AlterField(
            model_name='registrosigno',
            name='tipo_signo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='api.tiposigno'),
        ),
    ]
