# Generated by Django 6.1.1 on 2026-09-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_registrosigno_responsable_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paciente",
            options={"verbose_name": "Paciente", "verbose_name_plural": "Pacientes"},
        ),
        migrations.AlterModelTable(
            name="paciente",
            table="pacientes",
        ),
    ]
